### ISSUE TITLE
unauthorized: User not found or access denied.

### ISSUE THREAD

**Issue by d4rkd0s** [TheoKouzelis/laravel-airbrake#1]
My Handler.php
```
public function report(Exception $e)
    {
        // For airbrake exception handling
        $airbrakeNotifier = \App::make('Airbrake\Notifier');
        $return = $airbrakeNotifier->notify($e);
        Log::debug($return);

        // Normal Exception reporting
        parent::report($e);
    }
```

The "return"
```
[2017-04-25 15:49:41] local.DEBUG: array (
  'error' => 'unauthorized: User not found or access denied.',
)
```

**Comment by d4rkd0s** [comment]
My `config/airbrake.php`

```
<?php
return [
    'id'  => '14****',
    'key' => '0989b************************09b8'
];
```

***'s for omitting secret data

**Comment by d4rkd0s** [comment]
Composer successfully installed 
```
  - Installing airbrake/phpbrake (v0.0.12)
    Downloading: 100%

  - Installing kouz/laravel-airbrake (0.2)
    Downloading: 100%
```

and the config was published fine, and filled out in the above comment /\ 
```
$ php artisan vendor:publish --provider="Kouz\Providers\AirbrakeServiceProvider"
Copied File [\vendor\kouz\laravel-airbrake\config\airbrake.php] To [\config\airbrake.php]
Publishing complete for tag []!
```

**Comment by d4rkd0s** [comment]
I am using the information from here on Airbrake:

![Airbrake](http://i.imgur.com/sgnry6F.png)

**Comment by d4rkd0s** [comment]
So I guess the API key was changed due to some unforeseen circumstances with Airbrake. This issue can be closed.

**Comment by TheoKouzelis** [comment]
@d4rkd0s Sorry I didn't get to this on the day. Just to make sure I understand your issue correctly. It was due to your API Key changing in Airbrake, from what you had saved in your config\airbrake.php?

**Comment by d4rkd0s** [comment]
Yeah it was kinda weird, I was given a key upon signup. But that isn't the same as the project key. I understand it now, but it was a bit confusing at the time. Don't know if there is anything you can do in the repo besides maybe adding my example screenshot to the README.md under Setup. @TheoKouzelis
