### ISSUE TITLE
Is it sending user attributes to Errbit?

### ISSUE THREAD

**Issue by ugurarici** [TheoKouzelis/laravel-airbrake#10]
I integrated this package with Laravel 6.6.0 and now can track errors on Errbit, thank you.

But on Errbit I can't see User details. All Laravel routes are api routes so I use api auth.

I wonder if this package sends current logged in user details with exception or not. If sends, is my problem based on api auth? I checked controller method where I created an error, I can access logged in user detail with auth()->user() but it is not included in HTTP request parameters where laravel-airbrake sent to Errbit server.

**Comment by TheoKouzelis** [comment]
Hello @ugurarici 

This package is really a very slim wrapper around https://github.com/airbrake/phpbrake. Mostly it setups airbrake with the airbrake monolog handler, which is in the same repo. I know from experience that airbrake records a lot of data from PHP super globals whenever you create a notice, but you will have to look at the source code of that repo to see if it will do want you want.

**Comment by ugurarici** [comment]
Ok, I checked and found the solution [here](https://github.com/airbrake/phpbrake/blob/38c914a1d652f0ba9a0c0c8e52c0eff4242ae90c/README.md#add-user-data-to-the-notice). Thank you.

So, at `app/Exceptions/Handler.php` file's `report` method I added this after initializing `$airbrakeNotifier`

```
if($user = auth()->user()) {
    $airbrakeNotifier->addFilter(function ($notice) use ($user) {
        $notice['context']['user']['id'] = $user->id;
        $notice['context']['user']['name'] = $user->username;
        $notice['context']['user']['email'] = $user->email;
        return $notice;
    });
}
```

So in final it looked like this and worked like charm :)

```
public function report(Exception $exception)
{
    if ($this->shouldReport($exception)) {
        $airbrakeNotifier = \App::make('Airbrake\Notifier');
        if($user = auth()->user()) {
            $airbrakeNotifier->addFilter(function ($notice) use ($user) {
                $notice['context']['user']['id'] = $user->id;
                $notice['context']['user']['name'] = $user->username;
                $notice['context']['user']['email'] = $user->email;
                return $notice;
            });
        }
        $airbrakeNotifier->notify($exception);
    }
    
    parent::report($exception);
}
```
