### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> $opt ]] in class Airbrake\Notifier

### ISSUE THREAD

**Issue by devedup** [TheoKouzelis/laravel-airbrake#17]
On executing composer update

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Container.php line 1057:
                                                                                                   
  Unresolvable dependency resolving [Parameter #0 [ <required> $opt ]] in class Airbrake\Notifier

**Comment by devedup** [comment]
Sorted...

I tried by running:
php artisan clear-compiled

Which didn't work. So had to manually delete:
bootstrap/cache/*

**Comment by devedup** [comment]
Actually, I'm having to do this each time I'm running composer update. 

I'm not a PHP expert - but this doesn't seem normal? Is it something to do with this package?

**Comment by TheoKouzelis** [comment]
Hi @devedup 

Can you show me how you are using this package. For example are you using the "Custom Channel", the "Exception Handler" or the "Monolog Configuration. 

Can you also provide the version of PHP and Laravel please and a full stack trace.

**Comment by devedup** [comment]
PHP 7.3.21, however same issue on 7.4.9 

It's happening since I update to Laravel 8.31.0 

Not quite a stack trace, but this is what I get at the end of composer update:

```
remote: Generating optimized autoload files        
remote: > Illuminate\Foundation\ComposerScripts::postAutoloadDump        
remote: > @php artisan package:discover        
remote: 
remote: In Container.php line 1057:        
remote:                                                                                        
remote:   Unresolvable dependency resolving [Parameter #0 [ <required> $opt ]] in cla          
remote:   ss Airbrake\Notifier                                                                 
remote:                                                                                        
remote: 
remote: Running Opimizations        
remote: 
remote: In Container.php line 1057:        
remote:                                                                                        
remote:   Unresolvable dependency resolving [Parameter #0 [ <required> $opt ]] in cla          
remote:   ss Airbrake\Notifier                                                                 
remote:                                                                                        
remote: 
remote: 
remote: In Container.php line 1057:        
remote:                                                                                        
remote:   Unresolvable dependency resolving [Parameter #0 [ <required> $opt ]] in cla          
remote:   ss Airbrake\Notifier                                                                 
remote:                                                                                        
remote: 
remote: 
remote: In Container.php line 1057:        
remote:                                                                                        
remote:   Unresolvable dependency resolving [Parameter #0 [ <required> $opt ]] in cla          
remote:   ss Airbrake\Notifier                                                                 
remote:                                                                                        
remote: 
remote: Done  
```

I'm using both the Monolog config:

'airbrake' => [
            'driver' => 'custom',
            'via' => Kouz\LaravelAirbrake\AirbrakeLogger::class,
            'level' => 'error',
        ],


and in the report exception handler in Handler.php

public function report(Throwable $e)
    {
        if ($this->shouldReport($e)) {
            $airbrakeNotifier = \App::make('Airbrake\Notifier');
            $airbrakeNotifier->notify($e);
        }
        parent::report($e);
    }

It's all been working perfectly - just noticed this error now trying to do a composer update.

**Comment by TDiblik** [comment]
Hi, did you resolved your issue? I am currently looking at the same problem...
Thanks

**Comment by TheoKouzelis** [comment]
I haven't been able to replicate this issue
