### ISSUE TITLE
Update docs to reflect the new handler syntax

### ISSUE THREAD

**Issue by TheoKouzelis** [TheoKouzelis/laravel-airbrake#19]
```
if ($this->shouldReport($throwable)) {
            $airbrakeNotifier = App::make('Airbrake\Notifier');
            $airbrakeNotifier->notify($throwable);
}
```

**Comment by kevin-r-j** [comment]
Can I suggest that you also add an alternative condition to remind people they may not want this to fire on all environments

        if ((env('production') || env('staging')) && $this->shouldReport($throwable)) {
            $airbrakeNotifier = App::make('Airbrake\Notifier');
            $airbrakeNotifier->notify($throwable);
        }

**Comment by TheoKouzelis** [comment]
Now in the docs https://github.com/TheoKouzelis/laravel-airbrake/commit/02bdf9e7ef35959f7ec7974c7e3cd14eb10ed5c4
