### ISSUE TITLE
Upgrading to new versions of phpbrake with support for 'host'

### ISSUE THREAD

**Issue by csoutham** [TheoKouzelis/laravel-airbrake#2]
Hi, I've come across a scenario where host needs passing into the config.
This is supported in later version of phpbrake but not with the current composer requirements, are you happy for me to submit a PR request?

**Comment by TheoKouzelis** [comment]
Hi Chris

Yes please, that would be great. Thanks

Ross



From: Chris Southam
Sent: Saturday 29 July 14:17
Subject: [TheoKouzelis/laravel-airbrake] Upgrading to new versions of phpbrake with support for 'host' (#2)
To: TheoKouzelis/laravel-airbrake
Cc: Subscribed


Hi, I've come across a scenario where host needs passing into the config.
This is supported in later version of phpbrake but not with the current composer requirements, are you happy for me to submit a PR request?
