### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by wjgilmore** [TheoKouzelis/laravel-airbrake#3]
Hi,

We're currently evaluation application monitoring providers, and have narrowed the decision down to Rollbar and Airbrake. Any experience integrating your package with Lumen? Similar solutions for Rollbar don't work with Lumen due to service provider conflicts. Of course, we can manually integrate either using the respective service's PHP package; just looking for the most seamless solution. Thanks! -Jason

**Comment by TheoKouzelis** [comment]
Hi @wjgilmore 

I have never used this package with Lumen, but having had a quick look at the docs, I can't see why the Service Provider wouldn't work in Lumen. 

But in the case it didn't, the package supports direct instantiation to support custom [Monolog configurations](https://github.com/TheoKouzelis/laravel-airbrake#custom-monolog-configuration) by passing the Application model into  the [AirbrakeHandler class](https://github.com/TheoKouzelis/laravel-airbrake/blob/master/src/AirbrakeHandler.php).

But failing that, you could always just use Airbrakes package directly and just make sure you are filtering all the sensitive variables set in you .env file.

**Comment by TheoKouzelis** [comment]
@cesuarez  OK thanks I will take a look at that

**Comment by darkcarnage** [comment]
Hi,

Can someone give an example of Lumen integration ? I added `config_path()` function to a helpers.php file but still having the same error :

`Uncaught Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $opt ]] in class Airbrake\Notifier in /vendor/laravel/framework/src/Illuminate/Container/Container.php:993`

PS. It is the same error when using the Exception Handler or when calling `php artisan vendor:publish --provider="Kouz\LaravelAirbrake\ServiceProvider"`

Thanks.

**Comment by TDiblik** [comment]
Hi @darkcarnage did you find a solution? I'm currently dealing with the same issue

Thanks

**Comment by darkcarnage** [comment]
Hi @TDiblik, no I finallay switched to another error monitoring solution.

**Comment by TDiblik** [comment]
Oh, okay, I was able to solve ti actually, by using: https://github.com/airbrake/phpbrake
I just putted this code:
`
// Create new Notifier instance.
$notifier = new Airbrake\Notifier([
    'projectId' => 12345, // FIX ME
    'projectKey' => 'abcdefg' // FIX ME
]);

// Set global notifier instance.
Airbrake\Instance::set($notifier);
Airbrake\Instance::notify($e);
`
inside the exception handler... Not the best practice but it works....
Just putting it out there if somebody finds out while looking for answear 👍
